### ISSUE TITLE
Measures of entropy

### ISSUE THREAD

**Issue by tmcw** [tmcw/entropy#2]
@seandalby what's the most common way to measure the entropy of something like a stream of numbers?

**Comment by seandalby** [comment]
ah, sorry man I don't know that much about entropy... yet at least. maybe our program will touch on it some but I'll let you know in any case.

**Comment by tmcw** [comment]
https://github.com/aschuch/node-entropy

**Comment by tmcw** [comment]
NIST has a test, which is cool: http://csrc.nist.gov/groups/ST/toolkit/rng/documentation_software.html
